[package]
name = "rustgnuciverba"
version = "0.1.0"
authors = ["mone27 <mone.massaro@gmail.com>"]

[lib]
name = "rustgnuciverba"
path = "src/lib.rs"
test = true

[dependencies]
rand = "*"
ndarray = "0.12.0"