[package]
name = "rustgnuciverba"
version = "0.1.0"
authors = ["mone27 <mone.massaro@gmail.com>"]
edition = "2018"
[lib]
name = "rustgnuciverba"
path = "src/lib.rs"
test = true

[dependencies]
rand = "0.8.5"
ndarray = "0.15.6"
